### ISSUE TITLE
Лишнее ветвление

### ISSUE THREAD

**Issue by banyrule** [AishSI/rectangles#3]
https://github.com/AishSI/rectangles/blob/557446843c7ac264feea548e72ccb915673d2a44/RectanglesTask.cs#L21

После `if (!AreIntersected(r1, r2)) return 0;` можно не писать `else`, чтобы уменьшить уровень вложенности.

Другими словами ты вначале делаешь проверки на граничные случай, и если это не он, то идешь по стандартному пути вычисления

**Comment by AishSI** [comment]
Дошло. Я просто как-то не учел, что return не только получает значение, но и выбрасывает из метода...

**Comment by banyrule** [comment]
Кстати если у тебя встречает что-то вроде 

```csharp
if (cond) return x;
return y;

```
Лучше это офрмить через тернарный оператор:
```csharp
return cond
    ? x
    : y;
```
