### ISSUE TITLE
Повторение кода

### ISSUE THREAD

**Issue by banyrule** [AishSI/rectangles#6]
https://github.com/AishSI/rectangles/blob/557446843c7ac264feea548e72ccb915673d2a44/RectanglesTask.cs#L42

Можно обобщить первые два условия и записать весь метод в виде в виде:
```csharp
if (r1.IsInside(r2))
    return 0;
if (r2.IsInside(r1))
    return 1;

return -1;
```

**Comment by banyrule** [comment]
Ты уже знаком с методами расширения? Можно использовать их:
```csharp
public static class RectangleExtensions{
    public static bool IsInside(Rectangle this, Rectangle that) { ... };
}
```

**Comment by AishSI** [comment]
> IsInside(Rectangle this, Rectangle that)

Немного ввелся в заблудение этим this... потом уже лекцию посмотрел и сделал так:
`public static bool IsInside(this Rectangle inner, Rectangle outer)`
Без тхиса не обошелся, но теперь хоть понял, что это и зачем он в методах расширения. ;)

**Comment by banyrule** [comment]
Всё как я и хоте, отлично
